# Generated by Django 4.0.5 on 2022-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_is_active_alter_dealer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='tc',
            field=models.BooleanField(default=True),
        ),
    ]
