# Generated by Django 4.0.6 on 2022-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_tc_alter_dealer_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kt_id',
            field=models.CharField(default='KTCP{self.id}', max_length=50),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='kt_id',
            field=models.CharField(default='KTDK{self.id}', max_length=50),
        ),
    ]
